### ISSUE TITLE
Consolidate VC-AuthN instances

### ISSUE THREAD

**Issue by esune** [bcgov/trust-over-ip-configurations#126]
Until now we have been running two instances of VC-Authn (one under the default` profile and one under the `rev` profile) to support access requests with both non-revocable and revocable credentials, due to how the agents (mobile and enterprise) used to handle the requests.

After meticulous testing last week, it appears that only one use - case (presenting a non-revocable credential to a proof with a revocation interval) - yields inconsistent results across wallets, however most of the wallets and scenarios behave as expected.

We should move forward and consolidate the vc-authn instances asap in order to limit the number of moving components in the project, and the potential causes of confusion.

**Comment by WadeBarnes** [comment]
@esune, this is done now.  Correct?

**Comment by esune** [comment]
Yep, closing!
