### ISSUE TITLE
Remove PRIME, HG deployments

### ISSUE THREAD

**Issue by esune** [bcgov/trust-over-ip-configurations#129]
The Health gateway and PRIME agents are not being used, and should be decommissioned.

Complete the following steps:
- [x] save a back-up of the agent wallets
- [x] Remove entries from the backup configuration
  - [x] postgres=wallet-prime/agent_prime_wallet
  - [x] postgres=wallet-health-gateway/agent_health_gateway_wallet
- [x] spin down the deployments (@WadeBarnes / @esune )
- [x] remove configurations from repository/create tag for future reference (@WadeBarnes / @esune )
- [x] remove configurations from OCP (@WadeBarnes / @esune / @rajpalc7 )
- [x] close this issue (@WadeBarnes / @esune )

**Comment by esune** [comment]
The backup container already has backups for these components. I have spun down the deployments for both Prime and HG, passing this to back you @WadeBarnes and @rajpalc7 for next decommissioning steps.

**Comment by WadeBarnes** [comment]
Complete
