### ISSUE TITLE
Stuck in an error when accessing PROD ACM app

### ISSUE THREAD

**Issue by cvarjao** [bcgov/trust-over-ip-configurations#137]
I am getting a PROD lawyer credential + PROD person credential with a name mismatch. I was used to seeing a page showing that there is a name mismatch and the access would need to be approved. I am now getting a keycloak error page.

<img width="1030" alt="Screenshot 2023-06-15 at 9 59 58 AM" src="https://github.com/bcgov/vc-authn-oidc/assets/1348549/e17d135a-9c1c-4b1c-b89a-e24b312a05f4">

**Comment by esune** [comment]
Transferring issue to repository that holds the deployment configurations, rather than the product repo.

This doesn't look like an issue with `vc-authn`, but rather something that has to do with the integration with Keycloak.
@nikola-rados are you aware of this issue/can you help?

**Comment by cvarjao** [comment]
I also see that error when I click on "logout" from ACM app:

<img width="1027" alt="Screenshot 2023-06-15 at 4 10 12 PM" src="https://github.com/bcgov/trust-over-ip-configurations/assets/1348549/d5436485-402e-4a5a-8508-f81e16b004b6">

<img width="999" alt="Screenshot 2023-06-15 at 4 07 39 PM" src="https://github.com/bcgov/trust-over-ip-configurations/assets/1348549/976128cc-e73d-44df-831e-235fb9577346">

**Comment by esune** [comment]
@cvarjao @nikola-rados @WadeBarnes have you heard anything back from ACM regarding this? I am pretty confident this issue is NOT on our end and would be tempted to close the issue, but would like to confirm whether we have new information about this first.

**Comment by WadeBarnes** [comment]
I haven't heard any other complaints, but this does seem to correspond with the realm migration, so there might be something we need to tweak with the logoff.

**Comment by jleach** [comment]
I ran into this in ACM test today. Not much to add besides Kim saw this in prod with our "test" credential there. I see in the test environment regular. It did work before.

**Comment by knguyenBC** [comment]
I saw this again today using production credential in prod environment.

**Comment by nikola-rados** [comment]
I met with the keycloak team and have identified the cause of this problem. There are some subtle differences with how redirectUri's are handled in the new realm which is causing the error message. I am actively working on resolving this and will provide an update when I have a fix.

**Comment by WadeBarnes** [comment]
@nikola-rados, Do you have an update?

**Comment by WadeBarnes** [comment]
Related information from @arcshiftsolutions:

https://github.com/bcgov/sso-keycloak/discussions/161

Essentially, in the new version you need to provide the `id token` and a parameter called `post_logout_redirect_uri`.  Previously it was only `redirect_uri`.

**Comment by WadeBarnes** [comment]
A fix for this issue has been deployed to `dev`, `test`, and `prod`.  @cvarjao, @knguyenBC, would one of you be able to test the login/logout process please?

cc, @esune, @jleach

**Comment by sturufous** [comment]
An OIDC id_token is a Javascript Web Token that proves the identity of a user at the time of authentication. This token may be sent to the logout URL to hint at the identity of the user who is logging out, at which time it is referred to as the id_token_hint. In a single-sign-on environment, this may cause the user to be signed out of multiple applications simultaneously. 

The id_token_hint is not always a mandatory parameter of the logout URL, but (based on this behaviour) it appears that the Gold realm requires it to be passed on logout. 

I made changes to the A2A and ACM logout processes that append the id_token_hint to the logout URL and this has fixed the issue in dev. Wade Barnes will be promoting them to production when they have been subject to rigorous testing.

**Comment by cvarjao** [comment]
Tested. And it is working again.

**Comment by WadeBarnes** [comment]
Thanks @cvarjao
