### ISSUE TITLE
Need to rotate the IDIM Revocation Registries after deploying ACA-Py 0.9.0

### ISSUE THREAD

**Issue by swcurran** [bcgov/trust-over-ip-configurations#142]
Two updates in ACA-Py 0.9.0 impact IDIM — some upgrades/fixes to the CL Signatures codebase, and the ability to rotate Revocation Registries. One of the fixes to CL Signatures addresses a bug that to fully address in a deployed environment requires rotating the RevRegs currently being used, so that all new issuances use the new RevRegs. To support rotating the RevRegs, a new endpoint has been added to the Admin API `/revocation/active-registry/{cred_def_id}/rotate`.  For the IDIM instances, this needs to be run once after 0.9.0 has been successfully deployed and tested.

How to invoke the endpoint is an interesting question best handled by devs and devops folks.  Easiest would be to run it as a one time event using the Swagger API or curl directly.  Alternatively, some code could be put into the app to allow triggering when needed — although care would have to be taken to make sure that the process ran once and only once.  There is a need to use this endpoint now, but is likely to never be needed again.

**Comment by marcos-carretero** [comment]
@WadeBarnes , will you perform this step during the upgrade or will my team?

**Comment by esune** [comment]
Replaced by https://github.com/bcgov/DITP-DevOps/issues/103
