### ISSUE TITLE
Reorganize Traction value files

### ISSUE THREAD

**Issue by esune** [bcgov/trust-over-ip-configurations#203]
The values files for Traction `dev` and `pr` are stored in the Traction repo, however the pattern we have established is to have all files in this repository for consistency. To complete this ticket:

* Delete [this file](https://github.com/bcgov/traction/blob/6b4e5d4b8ded58c2184d9e043c55570dcdbf9d75/deploy/traction/values-development.yaml) from the Traction repo.
* Port the changes applied in #225 to the values files in the `services` folder, and delete unnecessary files in `helm-values`.
* The `sandbox` deployment configs might remain in the `helm-values` folder until the deployment is switched over to use Argo.
* The `vc-authn` files in the `helm-values` folder should be deleted as well.
* Can the `monitoring` files in `helm-values` be removed?

**Comment by i5okie** [comment]
https://github.com/bcgov/trust-over-ip-configurations/pull/230
