### ISSUE TITLE
Create a new ACA-Py Agent deployment for IDIM and plan for more

### ISSUE THREAD

**Issue by swcurran** [bcgov/trust-over-ip-configurations#79]
We would like to create a deployment of an ACA-Py agent for IDIM that will be an issuer for the BC Gov Verified Person credential.  This should include the "normal" Dev / Test / Prod OpenShift workspaces, but the setup of IDIM will require some additional planning. 

Task one is provision the environments and deploy an ACA-Py instance into the Dev workspace that we turn over to IDIM to use.  They will provide the webhook URL, we'll given them a CANdy-Dev Endorser, and we'll provide API auth token.  If you want we can move this task to another Issue.

The bigger picture is a bit more complicated. We think we have a plan, but wanted to go over it here and get @WadeBarnes input.  Here are the needs:

* IDIM has 7 separate environments for the BC Services Card Mobile app and related services.
* Those environments are generally divided into Dev (3 environments), Test (3) and Prod (1).
* The general thinking is that we want 1 ACA-Py instance per IDIM environment right now as that will be the easiest way to manage the verifiable credential objects (DIDs, Schema, CredDefs, etc.).
   * Multi-tenant would be nice, but we're not there yet.

I don't think we want to have an OpenShift ACA-Py Dev/Test/Prod workspace set per IDIM instance -- that would be a lot of OpenShift environments.  Rather, I'm thinking that we configure one OpenShift workspace set to have multiple instances of ACA-Py in each, one for each corresponding IDIM Instance.  That would give us:

| OpenShift Workspace | IDIM Environment | ACA-Py Name | Ledger |
| --- | --- | --- | --- | 
| Dev | DEV| DEV | CANdy-Dev |
| Dev | DEV2 | DEV2 | CANdy-Dev |
| Dev| SIT | SIT | CANdy-Dev |
| Test | QA | QA| CANdy-Test |
| Test | Test | Test | CANdy-Test |
| Test | PreProd | PreProd | CANdy-Test |
| Prod | Prod | Prod | CANdy-Prod |

For each instance, we would need pods for:

* ACA-Py
* Postgres

For at least one of the Test environments and Prod (and perhaps for all...)

* Redis
* PersistentQueues

@ianco

**Comment by WadeBarnes** [comment]
Yes, this would definitely be a candidate for multitenancy.

That is exactly what we'd do, have a matching instance for each of the IDIM environments and deploy multiple instances into the `dev` and `test` environments.  My initial thoughts are the `dev` and test` instances of ACA-Py  could share their database and persistent queue resources.  If we're going to use persistent queues, I'd want to setup all of the environments the same, that way we don't get any surprises moving from one environment to the next.

The other consideration would be the cluster in which we deploy these services.  We have the `Trust Over IP` environments in the Sliver Cluster we're using currently for deploying these types of agents.  We're hosting the BuyBC, Health Gateway, LSBC, and Prime agents there.  However, there is also the option of the Gold Cluster which has DR failover (warm standby) capability between the Kamloops and Calgary data centers, which we may want to consider.

**Comment by swcurran** [comment]
Good ideas -- thanks Wade.  I like the idea of the environments sharing resources, as they are all going to low volume except production.  I think that Gold is a good candidate for this as this could become a high volume/high availability resource.  I think it depends on the effort to move to Gold when needed.  For the current plans (e.g. next year) I would not think the volume/robustness requires Gold, so it is more a question of are we blocking some other app with a higher requirement for Gold.

**Comment by ianco** [comment]
> Yes, this would definitely be a candidate for multitenancy.

There are some constraints with multitenancy, mainly:
- there is limited "per-tenant configuration", mainly the webhook url, all other aca-py settings are shared across all tenants
- we can't create DID's in tenants using seeds, only using aca-py's "create-wallet-did" function (we need to create a local DID, register it on the ledger, and then promote to the wallet's public DID)
- the controller has to provide the tenant's JWT token in addition to the aca-py admin api

Probably something else that I haven't thought of (the "unknown unknowns")

**Comment by swcurran** [comment]
Sounds good.  Please proceed with the requisition, and set up the the OpenShift Dev environment to have one ACA-Py instance, and let's get/give the information from/to the IDIM team.  We'll worry about the multiple ACA-Py's per OpenShift environment later.

Thanks!

**Comment by WadeBarnes** [comment]
I'll be deploying into our existing `Trust Over IP` environment so we skip the requisition step.

**Comment by marcos-carretero** [comment]
Adding in the BCSC Mobile App builds to the IDIM environment mapping.

OpenShift Workspace | IDIM Environment | IDIM Mobile App | ACA-Py Name | Ledger
-- | -- | -- | -- | --
Dev | DEV | DEV | DEV | CANdy-Dev
Dev | DEV2 | DEV | DEV2 | CANdy-Dev
Dev | SIT | DEV | SIT | CANdy-Dev
Test | PreProd | DEV | PreProd | CANdy-Test
Test | QA | QA | QA | CANdy-Test
Test | Test | Test | Test | CANdy-Test
Prod | Prod | Prod | Prod | CANdy-Prod

**Comment by swcurran** [comment]
FYI - I created this issue in the wrong repo. Don't know if we want to move it now, but I meant to open it in the DTS-DevOps repo.  I forgot the ZenHub defaults the "New Issuer" repo for a board...

**Comment by WadeBarnes** [comment]
This is actually the repo in which the configuration would be placed.  I need to rename the repo too.  It should be `trust-over-ip-configurations`

**Comment by swcurran** [comment]
Well there you go.  I saw the "a2a" and assumed it would be not be here. Renaming it would make it clear :-)

**Comment by WadeBarnes** [comment]
Note to self ... Use Askar storage.

**Comment by WadeBarnes** [comment]
The `dev` instance has been handed over to @marcos-carretero.  I have a little bit of cleanup and automation to do, but the basic pattern has been established for use with the other instances as needed.

**Comment by WadeBarnes** [comment]
`sit`, `qa`, and `prod` instances have all been created and are in use.

**Comment by WadeBarnes** [comment]
`dev` instance has been upgraded to aca-py 0.8.1 and postgres 14

**Comment by swcurran** [comment]
Close this?

**Comment by esune** [comment]
Closing, @WadeBarnes please reopen if necessary.
