### ISSUE TITLE
Deploy an new instance of Issuer Kit for BC VC Pilot credential

### ISSUE THREAD

**Issue by swcurran** [bcgov/trust-over-ip-configurations#84]
Please deploy a new instance of Issuer kit to issue a "BC VC Pilot" credential, with the following configuration. Once the main elements of the deployment is on Dev, we can revise the wording.  The following are the parameters that I think you will need for deployment:

- Issue a credential called "BCVCPilot" schema with the attributes: "name"emailAddress", "program" and "iss_dateint"
- Nice to have: The credential should be revokable with a RevReg size of 1000 credentials.
   - We can add that after initial deployment, if necessary.
- Use ledger CANdy-Dev for writing.
- Enable the email invitation, with a database for entering the information for sending.
   - Require that a user have an active email validation code 
   - So that all credential fields except "iss_datetime" about the Holder must be entered by the person Inviting the user.
- Don't include any other authentication to get the credential -- just the invitation code.
- In creating the credential, using the current date converted to an integer of the form "20220325" -- not a string.
- For the first cut, use the text from this instance of Issuer Kit "https://bcgov-citz-issuer.apps.silver.devops.gov.bc.ca/" for the invitation, landing page screen and post-issuance screen.
   - Please document where the text for this instance can be found so we can put in a PR to update it.
- Set the DNS for the landing page/site to "https://bcvcpilot.vonx.io"
- Set Clecio, Charles, John and myself as Admins for creating/sending/resending invitations on Dev, Test, and for Production - all except me.
- The flow should be:
  - Admin enters invitation/credential fields and sends email
  - Holder receives invitation and clicks link
  - Goes to landing page and clicks to continue
  - Since there is no other Auth except the invitation, goes to the "Enter Credential" form.
  - No data to enter, since all comes for the invitation data and the "Issue_dateint" is generated automagically
  - User clicks to continue
  - Confirmation screen - click to continue
  - QR code comes up, and then to issue flow
  - User taken to the post-issuance page
  - Done.
 
I think that's it.  Let me know if any of these settings are difficult, or if I have left anything off.

Please ask @esune as needed for guidance.
@WadeBarnes heads up on this.
@cvarjao heads up on this

Would like this deployed as soon as is reasonable -- hoping for sometime next week.

**Comment by wadeking98** [comment]
Currently the environment is up and running in dev:
issuer-admin: https://bcvcpilot-issuer-admin-dev.apps.silver.devops.gov.bc.ca/
issuer-web: https://bcvcpilot-issuer-dev.apps.silver.devops.gov.bc.ca/

More work is needed to get keycloak working

**Comment by swcurran** [comment]
What is needed, and is there an ETA (e.g. a day, week or month)?

Also interested in how well Issuer Kit supports what we are after out of the box?  Are there any features listed above that are not supported?

How do I get access to the Issuer Admin site?  I tried to log into the Issuer Admin site using my GitHub ID and was told I was not authorized (as expected). I think, when things are set up that I should do that, and then you do something in Keycloak to make that work the next time -- is that right?

**Comment by wadeking98** [comment]
@swcurran I've finished setting up keycloak, I just need the email address for yourself Clecio, Charles and John

**Comment by wadeking98** [comment]
ETA to have this completed is Tuesday at the latest

**Comment by swcurran** [comment]
Good stuff - thanks for the update :-)!

What email addresses do you need -- the ones associated with our GitHub accounts?

**Comment by wadeking98** [comment]
correct, just the github ones

**Comment by wadeking98** [comment]
Credential issuance functionality is working. You should now be able to issue and accept credentials using the issuer-admin page in dev here: https://bcvcpilot-issuer-admin-dev.apps.silver.devops.gov.bc.ca/

**Comment by wadeking98** [comment]
@jljordan42 @swcurran @CharlesMacpherson @cvarjao production instance is deployed and your github accounts have all been added to keycloak.
To test out the production environment go to: https://bcvcpilot-admin.vonx.io/
