### ISSUE TITLE
Define the text on the BC VC Pilot

### ISSUE THREAD

**Issue by swcurran** [bcgov/trust-over-ip-configurations#87]
@alexgmetcalf and Kim -- there are several places in the BC VC Pilot issuer that we can adjust the wording of the text visible to people.  Can you please take the words and provide new, improved, 100% better words?

I'm sending you an email invitation to the service so that you can try it out and see where the words to be changed come into play.

The specific chunks of text needed are:

- The email invitation, also found [here](openshift/templates/issuer-api/config/bcvcpilot/invite-email.html).
- The landing/acknowledgment page after clicking the link in the email, text also found [here](openshift/templates/issuer-web/config/bcvcpilot/terms-and-conditions.html).
- The "after issue credential" landing page (couldn't find it in the source code).

I suggest that you run through the process and as you do, copy the email text, landing page text, and post-issue page text and paste each into a google doc.  Then revise the text in the Google Doc and add a comment to this issue that includes the link to the Google Doc.  We (@wadeking98 or I) will do a pull request to the repo to apply your changes.

Let us know if you have any questions.

**Comment by esune** [comment]
Is this still needing work, or can it be closed?

**Comment by esune** [comment]
Closing as done, reopen if please appropriate.
