### ISSUE TITLE
BC VC Pilot -- remove the double email address?

### ISSUE THREAD

**Issue by swcurran** [bcgov/trust-over-ip-configurations#88]
Is there a way to remove the double entry of the email address in the Admin form?  Perhaps (yet another) a config setting that named the claim into which the email address should go?

**Comment by swcurran** [comment]
If we do this, I would think it should be a general feature of Issuer Kit, not a special case for BC VC Pilot.

**Comment by wadeking98** [comment]
Unfortunately @esune said this isn't possible to combine the invitation field and the survey js email field without changeing the underlying functionality of issuer-kit.

**Comment by swcurran** [comment]
Sounds good. Let’s leave this one for now.
