### ISSUE TITLE
Deploy ACA-Py (0.7.4-rc3 nope) 0.7.4-rc4 for LSBC agent and fix the Revocation Registry issue

### ISSUE THREAD

**Issue by swcurran** [bcgov/trust-over-ip-configurations#95]
@WadeBarnes , @ianco -- with ACA-Py 0.7.4-rc3, we are ready to upgrade the prod deployment of the LSBC issuer to use the new release, and once deployed, to correct the RevReg problem that they are experiencing.  Since this is a production problem going back more than 2 months, this is very high priority.

Please organize what has to happen for that and make that happen ASAP, so that all of the credentials that LSBC has revoked are seen as revoked.  I think this means doing these steps:

- update dev to use new release and verify
  - who does the verification and what needs to get verified?
  - notify Wade that we can move to test
- update test to use the new release and verify
  - who does the verification and what needs to get verified?
  - notify Wade that we can go to prod
- update prod to use the new release and verify
  - What testing is done for this
  - Notify LSBC that the update has been done (do we normally do this?  Do we normally notify them ahead of time?)
- Wade/Ian coordinate access to the issuer ACA-Py instance so that the new "fixRevReg" endpoint can be called
- Confirm that the ACA-Py state of the RevReg matches the ledger

Please let me know if I'm off base with the sequence, and what additional steps/people/notifications are needed to complete this.

We'd like to complete this is quickly as possible -- while being safe in going through the right steps.

Completing this by Monday morning would be really appreciated.  I'm hoping that is possible, but do not know.

**Comment by WadeBarnes** [comment]
I've been testing the fix in `dev`.  It does not seem to be working as expected.  Waiting for @ianco to review.

**Comment by swcurran** [comment]
An update to this issue following the deployment of 0.7.4-rc3 to dev and the discovery of a new problem in rc3.  Here are the actions we agreed to follow in getting a fix to the LSBC prod environment.

- @andrewwhitehead to address the bug in the 0.7.4-rc3 implementation - the missing maintenance of the `issuer_cred_rev_record` data.
- Once 0.7.4-rc4 is created, it will be deployed to dev, and the rev_reg that is currently not working. (@WadeBarnes -- do we have to wait for the new release to do this?). We will not immediately try to address the "out of sync" issue with the dev RevReg since it is unexpectedly worse off.
- Once 0.7.4-rc4 is on dev, Wade will try to replicate the "out of sync" issue (turn off access to the ledger, revoke a credential) and a fix using the latest RevReg. This might be hard because there are unlikely to be any issued credentials, let alone revoked credentials.
- Push release to `test` and try to fix the RevReg that has been marked Full.  Should work... 
- If possible, try to replicate the "out of sync" issue on test (turn off access to the ledger, revoke a credential in the "full" RevReg, reinstate ledger access and try to fix the ledger).
- Push to `prod` and see if we can fix the offending RevReg.

Please update this note as needed.  Feel free to comment @ianco

**Comment by ianco** [comment]
> * If possible, try to replicate the "out of sync" issue on test (turn off access to the ledger, revoke a credential in the "full" RevReg, reinstate ledger access and try to fix the ledger).

The easiest way to do this is to just accept the wrong TAA, i.e. in the "accept taa" endpoint, just paste in the wrong text.  Your next ledger write will get rejected.  So you can turn the ledger writes on & off essentially just using the "taa accept" endpoint.

(One of the taa integration tests uses this process)

**Comment by WadeBarnes** [comment]
The state on the affected Rev_Reg in `dev` has been set to full, so we can come back and fix it later.
