### ISSUE TITLE
Please add ACAPY_INVITE_PUBLIC env variable to true to IDIM config (startup param --invite-public)

### ISSUE THREAD

**Issue by swcurran** [bcgov/trust-over-ip-configurations#96]
To test, please add it to, and redeploy: 

https://github.com/bcgov/trust-over-ip-configurations/blob/main/openshift/templates/issuer-agent/issuer-agent-deploy.idim-sit.test.param

It's likely safe to add it to all of the IDIM controllers.

**Comment by WadeBarnes** [comment]
Done
