### ISSUE TITLE
BCVCPilot is broken

### ISSUE THREAD

**Issue by cvarjao** [bcgov/trust-over-ip-configurations#98]
It looks like there has been some recent update and the BC VC Pilot issuer is broken

- URLs are back being reusable (they should be one time use)
- The form is looks a bit weird (might just be me not remembering)

**Comment by swcurran** [comment]
@wadeking98 -- can you please jump on this one?  What has changed?

**Comment by wadeking98** [comment]
@cvarjao I haven't gotten to the URL reuse yet but the forms look weird because they're trying to pull the css from this endpoint which no longer exists `https://surveyjs.azureedge.net/1.5.13/survey.css`

**Comment by wadeking98** [comment]
okay it looks like the url needs to be replaced with `https://unpkg.com/survey-jquery/survey.css`
